# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

   config.vm.define "worker1" do |worker1|
     worker1.vm.box = "bento/ubuntu-20.04-arm64"
     worker1.vm.hostname = "worker1"
     worker1.vm.network "private_network", ip: "192.168.33.11"
     config.vm.provider "parallels" do |vb|
         vb.name = "worker1"
      end
      config.vm.provision "shell", inline: <<-SHELL
            sudo su
            sudo echo "worker1" > /etc/hostname
            sudo echo "192.168.33.10  master" >> /etc/hosts
            sudo echo "192.168.33.11  worker1" >> /etc/hosts
            sudo echo "192.168.33.12  worker2" >> /etc/hosts
       SHELL
   end

end
